version: "3"

services:
  print-api:
    build: 
      context: .
      dockerfile: ./.docker/easy-rch-printf-api.dockerfile
    environment:
      NATS_URL: nats://nats:4222
      NATS_STREAM_NAME: TEST
      NATS_SUBJECT: test
      LISTEN_AT: 0.0.0.0:3000
