basePath: /
definitions:
  main.PrintOrder:
    properties:
      products:
        items:
          $ref: '#/definitions/main.Product'
        type: array
    required:
    - products
    type: object
  main.Product:
    properties:
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    required:
    - name
    - price
    - quantity
    type: object
info:
  contact: {}
  description: Human and developer friendly API for the RCH Printer.
  license:
    name: MIT
  title: Easy RCH PrintF! API
  version: "1.0"
paths:
  /new-order:
    post:
      consumes:
      - application/json
      description: Creates a new print order.
      parameters:
      - description: New print order.
        in: body
        name: printOrder
        required: true
        schema:
          $ref: '#/definitions/main.PrintOrder'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.PrintOrder'
      summary: Creates a new print order.
swagger: "2.0"
